from __future__ import annotations


def register_web_api_routes(app, handlers: dict[str, callable], csrf, limiter, api_v1_rate_limit_key) -> None:
    """JSON APIs not covered by library, extension, or discovery core routes."""
    app.add_url_rule(
        "/api/library/duplicate-hints",
        endpoint="api_duplicate_hints",
        view_func=handlers["api_duplicate_hints"],
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/library/merge-bookmarks",
        endpoint="api_merge_bookmarks",
        view_func=csrf.exempt(handlers["api_merge_bookmarks"]),
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/library/chapter-map",
        endpoint="api_chapter_map",
        view_func=handlers["api_chapter_map"],
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/library/alt-sources",
        endpoint="api_alt_sources",
        view_func=handlers["api_alt_sources"],
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/image-proxy",
        endpoint="api_image_proxy",
        view_func=handlers["api_image_proxy"],
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/demo/track",
        endpoint="api_track_series",
        view_func=csrf.exempt(handlers["api_track_series"]),
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/demo/search",
        endpoint="api_public_search",
        view_func=handlers["api_public_search"],
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/track",
        endpoint="api_track_series_legacy_disabled",
        view_func=csrf.exempt(handlers["api_track_series_legacy_disabled"]),
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/search",
        endpoint="api_public_search_legacy_disabled",
        view_func=handlers["api_public_search_legacy_disabled"],
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/series/<int:series_id>/sources",
        endpoint="api_series_sources",
        view_func=handlers["api_series_sources"],
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/source-request",
        endpoint="api_source_request",
        view_func=csrf.exempt(handlers["api_source_request"]),
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/recent-updates",
        endpoint="api_recent_updates",
        view_func=handlers["api_recent_updates"],
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/discover/supported-sources",
        endpoint="api_discover_supported_sources",
        view_func=handlers["api_discover_supported_sources"],
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/discover/search",
        endpoint="api_discover_search",
        view_func=handlers["api_discover_search"],
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/discover/series/<int:series_id>",
        endpoint="api_discover_series",
        view_func=handlers["api_discover_series"],
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/discover/series/<int:series_id>/sources",
        endpoint="api_discover_series_sources",
        view_func=handlers["api_discover_series_sources"],
        methods=["GET"],
    )
    app.add_url_rule(
        "/api/tracker/add-series",
        endpoint="api_tracker_add_series",
        view_func=csrf.exempt(handlers["api_tracker_add_series"]),
        methods=["POST"],
    )

    v1_books = limiter.limit("60/minute", methods=["GET"], key_func=api_v1_rate_limit_key)(
        csrf.exempt(handlers["api_v1_bookmarks"])
    )
    app.add_url_rule("/api/v1/bookmarks", endpoint="api_v1_bookmarks", view_func=v1_books, methods=["GET"])

    app.add_url_rule(
        "/api/account/api-token",
        endpoint="api_account_issue_token",
        view_func=csrf.exempt(handlers["api_account_issue_token"]),
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/debug/scrape",
        endpoint="debug_scrape",
        view_func=csrf.exempt(handlers["debug_scrape"]),
        methods=["POST"],
    )
    app.add_url_rule(
        "/api/maintenance/merge-duplicates",
        endpoint="merge_duplicates",
        view_func=csrf.exempt(handlers["merge_duplicates"]),
        methods=["POST"],
    )
